'use client'

import Link from 'next/link'
import { ChevronRight, ExternalLink, Sparkles } from 'lucide-react'

interface DocumentViewHeaderProps {
  workspaceId: string
  workspaceName: string
  folderId: string
  folderName: string
  title: string
  autoGenerated?: boolean
  pageUrl?: string
  editable?: boolean
  onTitleChange?: (value: string) => void
  onTitleBlur?: () => void
}

export default function DocumentViewHeader({
  workspaceId,
  workspaceName,
  folderId,
  folderName,
  title,
  autoGenerated = false,
  pageUrl,
  editable = true,
  onTitleChange,
  onTitleBlur,
}: DocumentViewHeaderProps) {
  const displayTitle = title.trim() || 'Untitled'
  const folderHref = `/app/${workspaceId}/folder/${folderId}`
  const dashboardHref = `/app/${workspaceId}/dashboard`

  return (
    <header className="mb-8 space-y-4">
      <nav aria-label="Breadcrumb" className="flex min-w-0 flex-wrap items-center gap-1.5 text-sm">
        <Link
          href={dashboardHref}
          className="shrink-0 text-muted-foreground transition-colors hover:text-foreground"
        >
          {workspaceName}
        </Link>
        <ChevronRight className="h-3.5 w-3.5 shrink-0 text-muted-foreground/50" aria-hidden />
        <Link
          href={folderHref}
          className="shrink-0 text-muted-foreground transition-colors hover:text-foreground"
        >
          {folderName}
        </Link>
        <ChevronRight className="h-3.5 w-3.5 shrink-0 text-muted-foreground/50" aria-hidden />
        <span className="min-w-0 truncate font-medium text-foreground">{displayTitle}</span>
      </nav>

      <div className="space-y-3">
        {autoGenerated && (
          <div className="flex flex-wrap items-center gap-2">
            <span className="inline-flex items-center gap-1.5 rounded-full border border-amber-200 bg-amber-50 px-2.5 py-1 text-[11px] font-medium text-amber-800 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-300">
              <Sparkles className="h-3 w-3" aria-hidden />
              Auto-recap
            </span>
            {pageUrl && (
              <a
                href={pageUrl}
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-1.5 text-xs font-medium text-primary transition-opacity hover:opacity-80"
              >
                <ExternalLink className="h-3 w-3" aria-hidden />
                Open source page
              </a>
            )}
          </div>
        )}

        {editable ? (
          <input
            value={title}
            onChange={e => onTitleChange?.(e.target.value)}
            onBlur={onTitleBlur}
            className="w-full border-none bg-transparent text-3xl font-semibold tracking-tight text-foreground outline-none placeholder:text-muted-foreground/40"
            placeholder="Untitled"
            aria-label="Document title"
          />
        ) : (
          <h1 className="text-3xl font-semibold tracking-tight text-foreground leading-tight">
            {displayTitle}
          </h1>
        )}

        {autoGenerated && (
          <p className="text-sm text-muted-foreground">
            A detailed log of what you captured on the source page. Editable like any document — new captures still append on refresh.
          </p>
        )}
      </div>
    </header>
  )
}
